### PR TITLE
Making a fresh new build to resolve some building issues

### LINKED ISSUE #15: Issue with ffmpeg-python 0.2.0 at pip check

### PR DESCRIPTION
**Pull request by HeavyTony2**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes: https://github.com/conda-forge/ytmdl-feedstock/issues/15
When I updated the feedstock last week, I had to disable pip check because of the following message
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1082471&view=logs&j=7b6f2c87-f3a7-5133-8d84-7c03a75d9dfc&t=9eb77fd2-8ddd-5444-8fc0-71cb28dcb736&l=1443
```
+ pip check
ffmpeg-python 0.2.0 is not supported on this platform
```
I tried a few things locally and it seems the build is simply too old

Superseded by: #3

### CODE REVIEW

**Comment by HeavyTony2** [comment]
@conda-forge-admin, please rerender

**Comment by HeavyTony2** [comment]
@conda-forge-admin, please rerender

**Comment by HeavyTony2** [comment]
@conda-forge-admin, please ping team

**Comment by HeavyTony2** [comment]
superseded by: #3

**Comment by hmaarrfk** [comment]
Could you add yourself as a maintainer? I'll click merge when you do.

```
ffmpeg-python 0.2.0 is not supported on this platform
```

is typically set because some classifier is too strict?
https://github.com/kkroening/ffmpeg-python/blob/master/setup.py#L98

**Comment by mwcraig** [comment]
Closed by #3

**Pull request closed without merging**
